package checkoutview;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import javax.swing.table.DefaultTableModel;

public class CheckoutPanel extends javax.swing.JPanel {

    private BiConsumer<String, String> voidAction;
    private Consumer<String> scanAction;
    private Consumer<String> paymentAction;

    private final Consumer<String> totalDisplayAction;
    private final Consumer<String> cashDisplayAction;
    private final Consumer<String> changeDisplayAction;

    private final Consumer<LinkedHashMap<Product, Integer>> productDisplayAction;

    private Runnable newTransactionAction;

    private final DefaultTableModel tableModel;

    public CheckoutPanel() {
        initComponents();
        voidDialog.setLocationRelativeTo(null);
        paymentDialog.setLocationRelativeTo(null);
        voidDialog.pack();
        paymentDialog.pack();
        this.tableModel = (DefaultTableModel) productTable.getModel();

        totalDisplayAction = (total) -> {
            totalField.setText(total);
        };

        cashDisplayAction = (cash) -> {
            cashField.setText(cash);
        };

        changeDisplayAction = (change) -> {
            changeField.setText(change);
        };

        productDisplayAction = (cart -> {
            tableModel.setRowCount(0);

            for (var product : cart.keySet()) {
                int quantity = cart.get(product);

                BigDecimal price = BigDecimal.valueOf(product.getPrice());
                BigDecimal totalPrice = price.multiply(BigDecimal.valueOf(quantity)).setScale(2, BigDecimal.ROUND_HALF_UP);

                tableModel.addRow(new Object[]{
                    product.getName(),
                    price,
                    quantity,
                    totalPrice
                });
            }
        });
    }

    /**
     * Sets the action to be performed when the total amount needs to be
     * displayed in the GUI.
     *
     * @return The action to display the total amount.
     */
    public Consumer<String> getTotalDisplayAction() {
        return totalDisplayAction;
    }

    /**
     * Sets the action to be performed when the cash amount needs to be
     * displayed in the GUI.
     *
     * @return The action to display the cash amount.
     */
    public Consumer<String> getCashDisplayAction() {
        return cashDisplayAction;
    }

    /**
     * Sets the action to be performed when the change amount needs to be
     * displayed in the GUI.
     *
     * @return The action to display the change amount.
     */
    public Consumer<String> getChangeDisplayAction() {
        return changeDisplayAction;
    }

    /**
     * Sets the action to be performed when a void transaction is requested.
     *
     * @param voidAction The action to be executed when a void transaction is
     * requested.
     */
    public void setVoidAction(BiConsumer<String, String> voidAction) {
        this.voidAction = voidAction;
    }

    /**
     * Sets the action to be performed when a barcode is scanned.
     *
     * @param scanAction The action to be executed when a barcode is scanned.
     */
    public void setScanAction(Consumer<String> scanAction) {
        this.scanAction = scanAction;
    }

    /**
     * Sets the action to be performed when a payment is made.
     *
     * @param paymentAction The action to be executed when a payment is made.
     */
    public void setPaymentAction(Consumer<String> paymentAction) {
        this.paymentAction = paymentAction;
    }

    /**
     * Sets the action to be performed when a new transaction is started.
     *
     * @param newTransactionAction The action to be executed when a new
     * transaction is started.
     */
    public void setNewTransactionAction(Runnable newTransactionAction) {
        this.newTransactionAction = newTransactionAction;
    }

    /**
     * Retrieves the table model used by the GUI table to manage data.
     *
     * @return The table model.
     */
    public DefaultTableModel getTableModel() {
        return tableModel;
    }

    /**
     * Gets the action to be performed when displaying products and quantities
     * in the GUI table.
     *
     * @return The action to display products and quantities.
     */
    public Consumer<LinkedHashMap<Product, Integer>> getProductDisplayAction() {
        return productDisplayAction;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        voidDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voidBarcodeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        voidQuantityField = new javax.swing.JTextField();
        paymentDialog = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        salfjs = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        paymentCashField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barcodeField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cashField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        changeField = new javax.swing.JTextField();

        voidDialog.setTitle("Product Void");
        voidDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Confirm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);

        voidDialog.getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Barcode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 18);
        jPanel3.add(jLabel2, gridBagConstraints);

        voidBarcodeField.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 11);
        jPanel3.add(voidBarcodeField, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Quantity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 18);
        jPanel3.add(jLabel3, gridBagConstraints);

        voidQuantityField.setPreferredSize(new java.awt.Dimension(300, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 11);
        jPanel3.add(voidQuantityField, gridBagConstraints);

        voidDialog.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        paymentDialog.setTitle("Payment Input");
        paymentDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jButton6.setText("Confirm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);

        salfjs.setText("Cancel");
        salfjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salfjsActionPerformed(evt);
            }
        });
        jPanel7.add(salfjs);

        paymentDialog.getContentPane().add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Cash");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel6.add(jLabel4, gridBagConstraints);

        paymentCashField.setPreferredSize(new java.awt.Dimension(300, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        jPanel6.add(paymentCashField, gridBagConstraints);

        paymentDialog.getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout(10, 10));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Product Barcode");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        barcodeField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        barcodeField.setPreferredSize(new java.awt.Dimension(64, 70));
        barcodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeFieldActionPerformed(evt);
            }
        });
        jPanel1.add(barcodeField, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Pay");
        jButton1.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Void");
        jButton2.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("New Transaction");
        jButton3.setPreferredSize(new java.awt.Dimension(250, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        productTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Qty", "Sub Total"
            }
        ));
        productTable.setRowHeight(50);
        jScrollPane1.setViewportView(productTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(22, 22, 22, 22);
        jPanel4.add(jLabel5, gridBagConstraints);

        totalField.setEditable(false);
        totalField.setBackground(new java.awt.Color(255, 255, 255));
        totalField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalField.setPreferredSize(new java.awt.Dimension(300, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel4.add(totalField, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Cash");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jLabel6, gridBagConstraints);

        cashField.setEditable(false);
        cashField.setBackground(new java.awt.Color(255, 255, 255));
        cashField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cashField.setPreferredSize(new java.awt.Dimension(300, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel4.add(cashField, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Change");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(jLabel7, gridBagConstraints);

        changeField.setEditable(false);
        changeField.setBackground(new java.awt.Color(255, 255, 255));
        changeField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        changeField.setPreferredSize(new java.awt.Dimension(300, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel4.add(changeField, gridBagConstraints);

        add(jPanel4, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        voidDialog.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.voidDialog.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        voidDialog.hide();

        if (voidAction == null) {
            return;
        }

        voidAction.accept(voidBarcodeField.getText(), voidQuantityField.getText());
        voidBarcodeField.setText("");
        voidQuantityField.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void barcodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeFieldActionPerformed

        if (scanAction == null) {
            return;
        }

        scanAction.accept(barcodeField.getText());
        barcodeField.setText("");

    }//GEN-LAST:event_barcodeFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        paymentDialog.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salfjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salfjsActionPerformed
        paymentDialog.hide();
    }//GEN-LAST:event_salfjsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        newTransactionAction.run();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        paymentDialog.hide();

        if (paymentAction == null) {
            return;
        }

        paymentAction.accept(paymentCashField.getText());

    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcodeField;
    private javax.swing.JTextField cashField;
    private javax.swing.JTextField changeField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField paymentCashField;
    private javax.swing.JDialog paymentDialog;
    private javax.swing.JTable productTable;
    private javax.swing.JButton salfjs;
    private javax.swing.JTextField totalField;
    private javax.swing.JTextField voidBarcodeField;
    private javax.swing.JDialog voidDialog;
    private javax.swing.JTextField voidQuantityField;
    // End of variables declaration//GEN-END:variables
}
