
package checkoutview;

import java.awt.BorderLayout;


public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        
        CheckoutPanel checkoutPanel = new CheckoutPanel();
        
        checkoutPanel.setScanAction((barcode)->{
            System.out.println("Barcode Input: "+barcode);
            checkoutPanel.getCashDisplayAction().accept(barcode + " Cash");
            checkoutPanel.getChangeDisplayAction().accept(barcode + " Change");
            checkoutPanel.getTotalDisplayAction().accept(barcode + " Total");
        });
        
        
        this.getContentPane().add(checkoutPanel,BorderLayout.CENTER);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
